config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "homes#top"
  resources :snacks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snack.rb
class Snack < ApplicationRecord

  validates :title, presence: true
  validates :category, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  def index
    @snacks = Snack.all
    @snack = Snack.new
  end

  def show
    @snack = Snack.find(params[:id])
  end

  def create
    @snack = Snack.new(snack_params)
    if @snack.save
      flash[:notice] = "Snack was successfully created."
      redirect_to snack_path(@snack.id)
    else
      @snacks = Snack.all
      render :index
    end
  end

  def edit
    @snack = Snack.find(params[:id])
  end

  def update
    snack = Snack.find(params[:id])
    if flash[:notice] = "Snack was successfully created."
      snack.update(snack_params)
      redirect_to snack_path(snack)
    else
      render :edit
    end
  end

  def destroy
    snack = Snack.find(params[:id])
    snack.destroy
    redirect_to snacks_path
  end

  private

  def snack_params
    params.require(:snack).permit(:title, :category, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/views/homes/top.html.erb
<h1>EXAM<h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EXAM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/snacks/edit.html.erb
<h2>商品説明変更等</h2>
<%= form_with model: @snack, local: true do |f| %>
  <h4>商品名</h4>
  <%= f.text_field :title %>
  <h4>カテゴリー</h4>
  <%= f.text_field :category %>
  <h4>商品説明</h4>
  <%= f.text_area :body %>
  <br><%= f.submit "Update snack" %></br>
<% end %>

<%= link_to "Show", snack_path(@snack) %>
<%= link_to "Back", snacks_path %>

app/views/snacks/index.html.erb
<h3>Snack</h3>
<table>
  <thead>
    <tr>
      <th>title<th>
      <th>category</th>
      <th>body</th>
    </tr>
  </thead>

  <tbody>

  <% @snacks.each do |snack| %>
    <tr>
      <td>
        <%= snack.title %>
      </td>
      <td>
        <%= snack.category %>
      </td>
      <td>
        <%= snack.body %>
      </td>
      <td>
        <%= link_to "Show", snack_path(snack) %>
        <%= link_to "Edit", edit_snack_path(snack) %>
        <%= link_to "Delete", snack_path(snack), method: :delete %>
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

<h4>New Snack</h4>

<% if @snack.errors.any? %>
  <%= @snack.errors.count %>errors prohibited this snack from being save:
  <% @snack.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model: @snack, local: true do |f| %>
  <h5>商品名</h5>
  <%= f.text_field :title %>
  <h5>カテゴリー</h5>
  <%= f.text_field :category %>
  <h5>商品説明</h5>
  <%= f.text_area :body %>
  <br><%= f.submit "Create Snack" %></br>
<% end %>

app/views/snacks/show.html.erb
<% if flash[:notice] %>
  <p>
    <%= flash[:notice] %>
  </p>
<% end %>
<h2>商品名</h2>
<%= @snack.title %>
<h2>カテゴリー</h2>
<%= @snack.category %>
<h2>商品説明</h2>
<%= @snack.body %>
<br></br>
<%= link_to "Edit", edit_snack_path(@snack) %>
<%= link_to "Back", snacks_path %>